// 就活で気をつけるべきポイント、豆知識、雑学のデータ

export type TipCategory = 'job_hunting' | 'trivia' | 'knowledge';

export interface Tip {
  category: TipCategory;
  content: string; // 2行で完結する内容
}

// ①就活で気をつけるべきポイント（50個）
const jobHuntingTips: Tip[] = [
  { category: 'job_hunting', content: '面接では第一印象が重要。\n清潔感のある服装と明るい表情を心がけましょう。' },
  { category: 'job_hunting', content: 'エントリーシートは簡潔に、でも具体的に。\n数字や具体例を入れることで、説得力が増します。' },
  { category: 'job_hunting', content: '企業研究は深く、広く行いましょう。\n会社の理念や最近のニュースもチェックしておくと良いです。' },
  { category: 'job_hunting', content: '自己分析は就活の基礎。\n自分の強みや弱みを理解しておくことが重要です。' },
  { category: 'job_hunting', content: 'OB・OG訪問は貴重な情報源。\n実際に働いている人の生の声を聞くことで、企業の雰囲気が分かります。' },
  { category: 'job_hunting', content: '複数の企業に応募するのは当然ですが、\nそれぞれの企業に合わせて志望動機をカスタマイズしましょう。' },
  { category: 'job_hunting', content: '面接の練習は必ず行いましょう。\n鏡の前で練習したり、友人や家族に協力してもらうと効果的です。' },
  { category: 'job_hunting', content: '時間管理は就活成功の鍵。\n説明会や面接のスケジュールをしっかり管理して、遅刻は絶対に避けましょう。' },
  { category: 'job_hunting', content: '質問は積極的にしましょう。\n面接の最後に「何か質問はありますか？」と聞かれた時、何も聞かないのはNGです。' },
  { category: 'job_hunting', content: 'メールのマナーも重要。\n件名は分かりやすく、本文は簡潔に、そして必ず署名を入れましょう。' },
  { category: 'job_hunting', content: 'グループディスカッションでは、\n自分の意見を押し通すのではなく、チーム全体の意見をまとめる姿勢が評価されます。' },
  { category: 'job_hunting', content: '失敗を恐れずにチャレンジすることが大切です。\n面接で落ちても、それは経験として次に活かせます。' },
  { category: 'job_hunting', content: '志望動機は「なぜその企業なのか」を明確に。\n「なぜその業界なのか」だけでなく、「なぜその企業なのか」を説明できるように。' },
  { category: 'job_hunting', content: '服装は業界によって適切なものが異なります。\n金融やコンサルはスーツ、ITやクリエイティブはカジュアルな場合も。' },
  { category: 'job_hunting', content: 'ポートフォリオや作品集がある場合は、\n面接で見せられるように準備しておくと良いです。' },
  { category: 'job_hunting', content: '面接では「ありがとうございます」を忘れずに。\n入室時、退室時、そして質問への回答の後にも感謝の気持ちを伝えましょう。' },
  { category: 'job_hunting', content: 'ストレス管理も重要。\n就活は長丁場なので、適度に息抜きをして、心身の健康を保ちましょう。' },
  { category: 'job_hunting', content: 'ネットの情報だけでなく、\n実際に企業説明会やインターンに参加して、自分の目で確かめることが大切です。' },
  { category: 'job_hunting', content: '面接では「聞く姿勢」も評価されます。\n質問された内容をしっかり理解してから答えるようにしましょう。' },
  { category: 'job_hunting', content: 'エントリーシートの提出期限は厳守。\n締切ギリギリではなく、余裕を持って提出しましょう。' },
  { category: 'job_hunting', content: '自己PRは具体的なエピソードとともに。\n「リーダーシップがある」だけでなく、「どのような場面で発揮したか」を説明できるように。' },
  { category: 'job_hunting', content: '面接では緊張するのは当然。\nでも、深呼吸をして、落ち着いて話すことを心がけましょう。' },
  { category: 'job_hunting', content: '企業の求める人材像を理解しておくことが重要。\n企業のホームページや採用情報をしっかり読んで、自分とのマッチングを考えましょう。' },
  { category: 'job_hunting', content: '面接の準備として、\n想定質問とその回答を準備しておくと、本番で慌てずに済みます。' },
  { category: 'job_hunting', content: '就活は情報戦でもあります。\n就活サイトや企業の公式サイトをこまめにチェックして、最新情報を入手しましょう。' },
  { category: 'job_hunting', content: '面接では「逆質問」の準備も大切。\n企業への質問を通じて、あなたの熱意や関心度が伝わります。' },
  { category: 'job_hunting', content: 'エントリーシートは誤字脱字に注意。\n提出前に必ず見直しをして、完璧な状態で提出しましょう。' },
  { category: 'job_hunting', content: '面接では「なぜその職種なのか」も説明できるように。\n営業、マーケティング、開発など、具体的な職種への志望動機も準備しておきましょう。' },
  { category: 'job_hunting', content: '就活は長期戦。\n焦らず、自分のペースで進めることが大切です。周りと比較しすぎないようにしましょう。' },
  { category: 'job_hunting', content: '面接では「失敗談」も聞かれることがあります。\n失敗から何を学んだか、どう改善したかを説明できるように準備しておきましょう。' },
  { category: 'job_hunting', content: '企業説明会では積極的に質問を。\n説明会での質問は、あなたの熱意を示す良い機会です。' },
  { category: 'job_hunting', content: '面接では「将来のキャリアプラン」も聞かれることが多いです。\n5年後、10年後の自分をイメージして、具体的に答えられるようにしましょう。' },
  { category: 'job_hunting', content: 'エントリーシートは手書きとPC入力、\nどちらが指定されているか確認してから作成しましょう。' },
  { category: 'job_hunting', content: '面接では「企業への貢献」をアピールすることが大切。\n自分が入社したら、どのように企業に貢献できるかを考えておきましょう。' },
  { category: 'job_hunting', content: '就活では「自己理解」が最も重要。\n自分が何をしたいのか、何ができるのかを明確にしておくことが成功の鍵です。' },
  { category: 'job_hunting', content: '面接では「チームワーク」について聞かれることも多いです。\nグループワークやサークル活動での経験を具体例として準備しておきましょう。' },
  { category: 'job_hunting', content: 'エントリーシートは「読みやすさ」も重要。\n適切な段落分けや改行を使って、読みやすい構成にしましょう。' },
  { category: 'job_hunting', content: '面接では「ストレス耐性」について聞かれることもあります。\nストレスをどう乗り越えてきたか、具体的なエピソードを準備しておきましょう。' },
  { category: 'job_hunting', content: '就活では「業界研究」も欠かせません。\n業界の動向や課題を理解しておくことで、面接で深い話ができます。' },
  { category: 'job_hunting', content: '面接では「コミュニケーション能力」が評価されます。\n相手の話を聞く姿勢、自分の意見を伝える力、どちらも大切です。' },
  { category: 'job_hunting', content: 'エントリーシートは「オリジナリティ」も重要。\n他の人と同じような内容ではなく、自分らしさを出せるようにしましょう。' },
  { category: 'job_hunting', content: '面接では「志望度の高さ」が伝わるように。\n企業への熱意は、言葉だけでなく、態度や表情からも伝わります。' },
  { category: 'job_hunting', content: '就活では「ネットワーク作り」も大切。\n同じ就活生同士で情報交換をしたり、OB・OGとつながりを持ったりしましょう。' },
  { category: 'job_hunting', content: '面接では「改善力」も評価されます。\n過去の失敗から学び、改善してきた経験をアピールできるように準備しておきましょう。' },
  { category: 'job_hunting', content: 'エントリーシートは「簡潔さ」と「具体性」のバランスが重要。\n長々と書くのではなく、要点を絞って具体的に書きましょう。' },
  { category: 'job_hunting', content: '面接では「企業への質問」で差がつきます。\n表面的な質問ではなく、深く考えた質問をすることで、あなたの熱意が伝わります。' },
  { category: 'job_hunting', content: '就活では「継続力」も評価されます。\n長期的に取り組んだことや、諦めずに続けた経験をアピールできるように準備しておきましょう。' },
  { category: 'job_hunting', content: '面接では「柔軟性」も重要です。\n変化に対応できる力や、新しい環境に適応できる力をアピールしましょう。' },
  { category: 'job_hunting', content: 'エントリーシートは「自己分析」の結果を反映させましょう。\n自分の強みや経験を、企業が求める人材像と結びつけて書くことが大切です。' },
  { category: 'job_hunting', content: '面接では「主体性」が評価されます。\n指示を待つのではなく、自ら動ける経験をアピールできるように準備しておきましょう。' },
  { category: 'job_hunting', content: '就活は「準備」が全て。\n企業研究、自己分析、面接練習、どれも手を抜かずにしっかり準備することが成功への道です。' },
];

// ②豆知識（50個）
const triviaTips: Tip[] = [
  { category: 'trivia', content: '就活の「エントリーシート」は、\n企業によっては「ES」と略されることがあります。' },
  { category: 'trivia', content: '面接で「最後に何か質問はありますか？」と聞かれた時、\n「ありません」と答えるのは避けましょう。必ず質問を準備しておくことが大切です。' },
  { category: 'trivia', content: '就活の「インターンシップ」は、\n短期（1日〜1週間）と長期（1ヶ月以上）の2種類があります。' },
  { category: 'trivia', content: '「グループディスカッション」では、\n発言量よりも、チーム全体の議論をまとめる力が評価されることが多いです。' },
  { category: 'trivia', content: '就活の「説明会」と「面接」は別物。\n説明会は企業を知る場、面接は自分をアピールする場と理解しましょう。' },
  { category: 'trivia', content: '「エントリーシート」の文字数制限は、\n企業によって異なります。必ず指定された文字数を守りましょう。' },
  { category: 'trivia', content: '面接の「第一印象」は、\n最初の数秒で決まると言われています。清潔感と明るい表情を心がけましょう。' },
  { category: 'trivia', content: '就活の「OB・OG訪問」は、\n必ずしも必須ではありませんが、企業理解を深める良い機会です。' },
  { category: 'trivia', content: '「自己PR」では、\n「何をしたか」だけでなく、「なぜそれをしたか」「どう感じたか」も伝えると良いです。' },
  { category: 'trivia', content: '就活の「選考フロー」は、\n企業によって異なります。エントリー→書類選考→面接→内定が一般的です。' },
  { category: 'trivia', content: '面接の「逆質問」では、\n「給与はいくらですか？」などの直接的な質問は避け、仕事内容や企業文化について聞くのが良いです。' },
  { category: 'trivia', content: '「エントリーシート」は、\n手書きとPC入力、どちらが指定されているか確認してから作成しましょう。' },
  { category: 'trivia', content: '就活の「内定」と「内々定」は違います。\n内々定は正式な内定ではなく、採用予定の通知です。' },
  { category: 'trivia', content: '面接では「沈黙」も戦略的に使えます。\n質問を聞いて、少し考えてから答えることで、深く考えている印象を与えられます。' },
  { category: 'trivia', content: '「グループワーク」では、\n自分の意見を押し通すのではなく、チーム全体の意見をまとめる姿勢が評価されます。' },
  { category: 'trivia', content: '就活の「説明会」では、\n積極的に質問をすることで、あなたの熱意が企業に伝わります。' },
  { category: 'trivia', content: '「エントリーシート」の「志望動機」は、\n「なぜその企業なのか」を明確に書くことが大切です。' },
  { category: 'trivia', content: '面接の「服装」は、\n業界によって適切なものが異なります。金融やコンサルはスーツ、ITやクリエイティブはカジュアルな場合も。' },
  { category: 'trivia', content: '就活の「自己分析」は、\n一度だけでなく、何度も見直すことで、より深い自己理解ができます。' },
  { category: 'trivia', content: '「面接の練習」は、\n鏡の前で練習したり、友人や家族に協力してもらうと効果的です。' },
  { category: 'trivia', content: '就活の「情報収集」は、\n就活サイトだけでなく、企業の公式サイトやSNSもチェックすると良いです。' },
  { category: 'trivia', content: '「エントリーシート」は、\n誤字脱字に注意。提出前に必ず見直しをして、完璧な状態で提出しましょう。' },
  { category: 'trivia', content: '面接では「聞く姿勢」も評価されます。\n質問された内容をしっかり理解してから答えるようにしましょう。' },
  { category: 'trivia', content: '就活の「ストレス管理」も重要。\n就活は長丁場なので、適度に息抜きをして、心身の健康を保ちましょう。' },
  { category: 'trivia', content: '「自己PR」では、\n具体的なエピソードとともに、自分の強みを伝えることが大切です。' },
  { category: 'trivia', content: '就活の「企業研究」は、\n会社の理念や事業内容だけでなく、最近のニュースもチェックしておくと良いです。' },
  { category: 'trivia', content: '面接では「将来のキャリアプラン」も聞かれることが多いです。\n5年後、10年後の自分をイメージして、具体的に答えられるようにしましょう。' },
  { category: 'trivia', content: '「エントリーシート」は、\n「読みやすさ」も重要。適切な段落分けや改行を使って、読みやすい構成にしましょう。' },
  { category: 'trivia', content: '就活の「ネットワーク作り」も大切。\n同じ就活生同士で情報交換をしたり、OB・OGとつながりを持ったりしましょう。' },
  { category: 'trivia', content: '面接では「チームワーク」について聞かれることも多いです。\nグループワークやサークル活動での経験を具体例として準備しておきましょう。' },
  { category: 'trivia', content: '「エントリーシート」の提出期限は厳守。\n締切ギリギリではなく、余裕を持って提出しましょう。' },
  { category: 'trivia', content: '就活の「業界研究」も欠かせません。\n業界の動向や課題を理解しておくことで、面接で深い話ができます。' },
  { category: 'trivia', content: '面接では「ストレス耐性」について聞かれることもあります。\nストレスをどう乗り越えてきたか、具体的なエピソードを準備しておきましょう。' },
  { category: 'trivia', content: '「エントリーシート」は「オリジナリティ」も重要。\n他の人と同じような内容ではなく、自分らしさを出せるようにしましょう。' },
  { category: 'trivia', content: '就活の「準備」が全て。\n企業研究、自己分析、面接練習、どれも手を抜かずにしっかり準備することが成功への道です。' },
  { category: 'trivia', content: '面接では「改善力」も評価されます。\n過去の失敗から学び、改善してきた経験をアピールできるように準備しておきましょう。' },
  { category: 'trivia', content: '「エントリーシート」は「簡潔さ」と「具体性」のバランスが重要。\n長々と書くのではなく、要点を絞って具体的に書きましょう。' },
  { category: 'trivia', content: '就活の「継続力」も評価されます。\n長期的に取り組んだことや、諦めずに続けた経験をアピールできるように準備しておきましょう。' },
  { category: 'trivia', content: '面接では「柔軟性」も重要です。\n変化に対応できる力や、新しい環境に適応できる力をアピールしましょう。' },
  { category: 'trivia', content: '「エントリーシート」は「自己分析」の結果を反映させましょう。\n自分の強みや経験を、企業が求める人材像と結びつけて書くことが大切です。' },
  { category: 'trivia', content: '就活の「主体性」が評価されます。\n指示を待つのではなく、自ら動ける経験をアピールできるように準備しておきましょう。' },
  { category: 'trivia', content: '面接では「企業への質問」で差がつきます。\n表面的な質問ではなく、深く考えた質問をすることで、あなたの熱意が伝わります。' },
  { category: 'trivia', content: '「エントリーシート」の「志望動機」は、\n「なぜその職種なのか」も説明できるように準備しておきましょう。' },
  { category: 'trivia', content: '就活の「時間管理」は成功の鍵。\n説明会や面接のスケジュールをしっかり管理して、遅刻は絶対に避けましょう。' },
  { category: 'trivia', content: '面接では「志望度の高さ」が伝わるように。\n企業への熱意は、言葉だけでなく、態度や表情からも伝わります。' },
  { category: 'trivia', content: '「エントリーシート」は「数字や具体例」を入れることで、\n説得力が増します。抽象的な表現ではなく、具体的に書きましょう。' },
  { category: 'trivia', content: '就活の「失敗を恐れずにチャレンジ」することが大切です。\n面接で落ちても、それは経験として次に活かせます。' },
  { category: 'trivia', content: '面接では「コミュニケーション能力」が評価されます。\n相手の話を聞く姿勢、自分の意見を伝える力、どちらも大切です。' },
  { category: 'trivia', content: '「エントリーシート」の「自己PR」は、\n「リーダーシップがある」だけでなく、「どのような場面で発揮したか」を説明できるように。' },
  { category: 'trivia', content: '就活は「情報戦」でもあります。\n就活サイトや企業の公式サイトをこまめにチェックして、最新情報を入手しましょう。' },
  { category: 'trivia', content: '面接では「緊張するのは当然」です。\nでも、深呼吸をして、落ち着いて話すことを心がけましょう。' },
];

// ③雑学（50個）
const knowledgeTips: Tip[] = [
  { category: 'knowledge', content: '日本の就活は、\n3月1日の「解禁日」から本格的に始まります。' },
  { category: 'knowledge', content: '「エントリーシート」の文字数は、\n企業によって200文字から800文字まで様々です。' },
  { category: 'knowledge', content: '面接の「第一印象」は、\n最初の7秒で決まると言われています。' },
  { category: 'knowledge', content: '就活の「インターンシップ」は、\n参加することで選考で優遇される場合があります。' },
  { category: 'knowledge', content: '「グループディスカッション」では、\n発言量よりも、チーム全体の議論をまとめる力が評価されます。' },
  { category: 'knowledge', content: '就活の「説明会」は、\n企業によっては複数回開催されることがあります。' },
  { category: 'knowledge', content: '「エントリーシート」は、\n手書きとPC入力、どちらが指定されているか確認が必要です。' },
  { category: 'knowledge', content: '面接の「逆質問」では、\n「給与はいくらですか？」などの直接的な質問は避けましょう。' },
  { category: 'knowledge', content: '就活の「内定」と「内々定」は違います。\n内々定は正式な内定ではなく、採用予定の通知です。' },
  { category: 'knowledge', content: '「自己PR」では、\n「何をしたか」だけでなく、「なぜそれをしたか」「どう感じたか」も伝えると良いです。' },
  { category: 'knowledge', content: '就活の「選考フロー」は、\n企業によって異なります。エントリー→書類選考→面接→内定が一般的です。' },
  { category: 'knowledge', content: '面接では「沈黙」も戦略的に使えます。\n質問を聞いて、少し考えてから答えることで、深く考えている印象を与えられます。' },
  { category: 'knowledge', content: '「グループワーク」では、\n自分の意見を押し通すのではなく、チーム全体の意見をまとめる姿勢が評価されます。' },
  { category: 'knowledge', content: '就活の「説明会」では、\n積極的に質問をすることで、あなたの熱意が企業に伝わります。' },
  { category: 'knowledge', content: '「エントリーシート」の「志望動機」は、\n「なぜその企業なのか」を明確に書くことが大切です。' },
  { category: 'knowledge', content: '面接の「服装」は、\n業界によって適切なものが異なります。金融やコンサルはスーツ、ITやクリエイティブはカジュアルな場合も。' },
  { category: 'knowledge', content: '就活の「自己分析」は、\n一度だけでなく、何度も見直すことで、より深い自己理解ができます。' },
  { category: 'knowledge', content: '「面接の練習」は、\n鏡の前で練習したり、友人や家族に協力してもらうと効果的です。' },
  { category: 'knowledge', content: '就活の「情報収集」は、\n就活サイトだけでなく、企業の公式サイトやSNSもチェックすると良いです。' },
  { category: 'knowledge', content: '「エントリーシート」は、\n誤字脱字に注意。提出前に必ず見直しをして、完璧な状態で提出しましょう。' },
  { category: 'knowledge', content: '面接では「聞く姿勢」も評価されます。\n質問された内容をしっかり理解してから答えるようにしましょう。' },
  { category: 'knowledge', content: '就活の「ストレス管理」も重要。\n就活は長丁場なので、適度に息抜きをして、心身の健康を保ちましょう。' },
  { category: 'knowledge', content: '「自己PR」では、\n具体的なエピソードとともに、自分の強みを伝えることが大切です。' },
  { category: 'knowledge', content: '就活の「企業研究」は、\n会社の理念や事業内容だけでなく、最近のニュースもチェックしておくと良いです。' },
  { category: 'knowledge', content: '面接では「将来のキャリアプラン」も聞かれることが多いです。\n5年後、10年後の自分をイメージして、具体的に答えられるようにしましょう。' },
  { category: 'knowledge', content: '「エントリーシート」は、\n「読みやすさ」も重要。適切な段落分けや改行を使って、読みやすい構成にしましょう。' },
  { category: 'knowledge', content: '就活の「ネットワーク作り」も大切。\n同じ就活生同士で情報交換をしたり、OB・OGとつながりを持ったりしましょう。' },
  { category: 'knowledge', content: '面接では「チームワーク」について聞かれることも多いです。\nグループワークやサークル活動での経験を具体例として準備しておきましょう。' },
  { category: 'knowledge', content: '「エントリーシート」の提出期限は厳守。\n締切ギリギリではなく、余裕を持って提出しましょう。' },
  { category: 'knowledge', content: '就活の「業界研究」も欠かせません。\n業界の動向や課題を理解しておくことで、面接で深い話ができます。' },
  { category: 'knowledge', content: '面接では「ストレス耐性」について聞かれることもあります。\nストレスをどう乗り越えてきたか、具体的なエピソードを準備しておきましょう。' },
  { category: 'knowledge', content: '「エントリーシート」は「オリジナリティ」も重要。\n他の人と同じような内容ではなく、自分らしさを出せるようにしましょう。' },
  { category: 'knowledge', content: '就活の「準備」が全て。\n企業研究、自己分析、面接練習、どれも手を抜かずにしっかり準備することが成功への道です。' },
  { category: 'knowledge', content: '面接では「改善力」も評価されます。\n過去の失敗から学び、改善してきた経験をアピールできるように準備しておきましょう。' },
  { category: 'knowledge', content: '「エントリーシート」は「簡潔さ」と「具体性」のバランスが重要。\n長々と書くのではなく、要点を絞って具体的に書きましょう。' },
  { category: 'knowledge', content: '就活の「継続力」も評価されます。\n長期的に取り組んだことや、諦めずに続けた経験をアピールできるように準備しておきましょう。' },
  { category: 'knowledge', content: '面接では「柔軟性」も重要です。\n変化に対応できる力や、新しい環境に適応できる力をアピールしましょう。' },
  { category: 'knowledge', content: '「エントリーシート」は「自己分析」の結果を反映させましょう。\n自分の強みや経験を、企業が求める人材像と結びつけて書くことが大切です。' },
  { category: 'knowledge', content: '就活の「主体性」が評価されます。\n指示を待つのではなく、自ら動ける経験をアピールできるように準備しておきましょう。' },
  { category: 'knowledge', content: '面接では「企業への質問」で差がつきます。\n表面的な質問ではなく、深く考えた質問をすることで、あなたの熱意が伝わります。' },
  { category: 'knowledge', content: '「エントリーシート」の「志望動機」は、\n「なぜその職種なのか」も説明できるように準備しておきましょう。' },
  { category: 'knowledge', content: '就活の「時間管理」は成功の鍵。\n説明会や面接のスケジュールをしっかり管理して、遅刻は絶対に避けましょう。' },
  { category: 'knowledge', content: '面接では「志望度の高さ」が伝わるように。\n企業への熱意は、言葉だけでなく、態度や表情からも伝わります。' },
  { category: 'knowledge', content: '「エントリーシート」は「数字や具体例」を入れることで、\n説得力が増します。抽象的な表現ではなく、具体的に書きましょう。' },
  { category: 'knowledge', content: '就活の「失敗を恐れずにチャレンジ」することが大切です。\n面接で落ちても、それは経験として次に活かせます。' },
  { category: 'knowledge', content: '面接では「コミュニケーション能力」が評価されます。\n相手の話を聞く姿勢、自分の意見を伝える力、どちらも大切です。' },
  { category: 'knowledge', content: '「エントリーシート」の「自己PR」は、\n「リーダーシップがある」だけでなく、「どのような場面で発揮したか」を説明できるように。' },
  { category: 'knowledge', content: '就活は「情報戦」でもあります。\n就活サイトや企業の公式サイトをこまめにチェックして、最新情報を入手しましょう。' },
  { category: 'knowledge', content: '面接では「緊張するのは当然」です。\nでも、深呼吸をして、落ち着いて話すことを心がけましょう。' },
  { category: 'knowledge', content: '「エントリーシート」の文字数制限は、\n企業によって異なります。必ず指定された文字数を守りましょう。' },
];

// 全カテゴリーを統合
export const ALL_TIPS: Tip[] = [
  ...jobHuntingTips,
  ...triviaTips,
  ...knowledgeTips,
];

// カテゴリー別にランダムに取得する関数
export const getRandomTip = (category?: TipCategory): Tip => {
  if (category) {
    const categoryTips = ALL_TIPS.filter(tip => tip.category === category);
    return categoryTips[Math.floor(Math.random() * categoryTips.length)];
  }
  return ALL_TIPS[Math.floor(Math.random() * ALL_TIPS.length)];
};
